export const coreServiceReady = true;
export * from './curriculum';
export * from './dashboard';
export * from './gamification';
export * from './learning';
export * from './memory';
export * from './onboarding';
export * from './profile';
export * from './quiz';
export * from './settings';
export * from './social';
export * from './sentence';
export * from './point';
export * from './point-integration';
